[package]
name = "advtools"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14"
regex = "1.11"
num = "0.4"
hashbrown = "0.15"
rayon = "1.10"
forward_ref_generic = "0.2"
memoize = "0.5.1"
